### ISSUE TITLE
issue pushing artwork to openframe

### ISSUE THREAD

**Issue by pauloguerraf** [OpenframeProject/Openframe#16] opened 2016-06-02 21:39 UTC
hi guys, 

i have installed openframe on a raspberry pi 2. everything works perfect until I try to update the artwork displayed on the frame from the website. Nothing happens when I choose a new artwork from my collection unless I hit ctrl+C and restart openframe. Only then the new artwork is displayed. 
Is this an issue? or is this the way it should always work? any advice on how to get this working would be greatly appreciated. thank you!

paulo

**Comment by jmwohl** [comment] 2016-06-03 15:57
Hi Paulo —

Yeah, that's definitely not the way it should work. It sounds like the websocket connection isn't being kept alive between your frame and the server after the frame authenticates. It's a bit hard to diagnose these issues, but could be due to a weak wifi signal or underpowered wifi dongle, or possibly the network you're on is blocking the port used for the websocket connection.

You can print debug log by adding the DEBUG env variable when starting openframe:

```
DEBUG=* openframe
```

That may give you some clues as to what's going on.

**Comment by jmwohl** [comment] 2016-09-24 15:17
Closing until we have further info  — couldn't reproduce on a fresh install.

**Closed by jmwohl** 2016-09-24 15:17 UTC
